name: "Sprint automation"
description: "GitHub Action that updates the sprint planning according to staged pull requests"
author: "uman"
runs:
  using: "node16"
  main: "dist/main/index.js"
inputs:
  github_token:
    description: "The GITHUB_TOKEN secret"
    required: true
  update_pr_commits:
    description: "Updates all project issues related to all the commits of a PR"
    required: false
    default: "false"
branding:
  icon: git-pull-request
  color: green
